version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./redis/data:/data
    restart: on-failure
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
