version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly yes"]
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
