version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    restart: on-failure
    networks:
      - mysql-network

  flower:
    container_name: flower
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    networks:
      - mysql-network

networks:
  mysql-network:
    external:
      name: mysql-network
